#!/bin/zsh
# Airgapped MacOS User setup script for EntropyLab
# GENERATED FILE — do not edit by hand.
# Source of truth: docs/Airgapped MacOS User.md
# Regenerated by GitHub Action: extract-macos-user-script.yml
#
# Run from an admin account that already has a Secure Token.
# Install Chromium or Google Chrome from a verified .dmg BEFORE going offline.
set -euo pipefail

# Self-contained artifact. Prefer a release + SHA256SUMS.txt for real funds.
curl -fL -o /tmp/entropylab.html \
  https://raw.githubusercontent.com/OogaBoogaX/entropylab/rock/entropylab.html

# Prompt for the kiosk password instead of baking one into history.
echo "Password for the new standard user 'entropylab':"
read -s EL_PASS
echo

sudo sysadminctl -addUser entropylab \
  -fullName "EntropyLab" \
  -password "$EL_PASS" \
  -home /Users/entropylab \
  -shell /bin/zsh

unset EL_PASS

sudo mkdir -p /Users/entropylab/bin /Users/entropylab/Library/LaunchAgents
sudo cp /tmp/entropylab.html /Users/entropylab/entropylab.html
sudo chown -R entropylab:staff /Users/entropylab
sudo chmod 644 /Users/entropylab/entropylab.html
# Optional: lock the HTML so the standard user cannot overwrite it
sudo chflags uchg /Users/entropylab/entropylab.html

U=entropylab

sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeCloudSetup -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant SkipCloudSetup -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeSiriSetup -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeePrivacy -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeAppearanceSetup -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeScreenTime -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeAccessibility -bool true

sudo -u "$U" defaults write com.apple.Siri StatusMenuVisible -bool false
sudo -u "$U" defaults write com.apple.Siri SiriEnabled -bool false
sudo -u "$U" defaults write com.apple.dock show-recents -bool false
sudo -u "$U" defaults write com.apple.finder CreateDesktop -bool false

# Sleep image would write RAM to NVMe. Machine-wide; Self-Destruct restores this.
sudo pmset -a sleep 0 disablesleep 1 hibernatemode 0
sudo -u "$U" defaults write com.apple.screensaver idleTime -int 0
