#!/bin/zsh
# Airgapped MacOS User setup script for EntropyLab
# GENERATED FILE -- do not edit by hand.
# Source of truth: docs/Airgapped MacOS User.md
# Regenerated by GitHub Action: extract-macos-user-script.yml
#
# Run from an admin account that already has a Secure Token.
# Install Chromium or Google Chrome from a verified .dmg BEFORE going offline.
set -euo pipefail

# Self-contained artifact. Prefer a release + SHA256SUMS.txt for real funds.
curl -fL -o /tmp/entropylab.html \
  https://raw.githubusercontent.com/OogaBoogaX/entropylab/rock/entropylab.html

# Prompt for the kiosk password instead of baking one into history.
echo "Password for the new standard user 'entropylab':"
read -s EL_PASS
echo

sudo sysadminctl -addUser entropylab \
  -fullName "EntropyLab" \
  -password "$EL_PASS" \
  -home /Users/entropylab \
  -shell /bin/zsh

unset EL_PASS

sudo mkdir -p /Users/entropylab/bin /Users/entropylab/Library/LaunchAgents
sudo cp /tmp/entropylab.html /Users/entropylab/entropylab.html
sudo chown -R entropylab:staff /Users/entropylab
sudo chmod 644 /Users/entropylab/entropylab.html
# Optional: lock the HTML so the standard user cannot overwrite it
sudo chflags uchg /Users/entropylab/entropylab.html


U=entropylab

sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeCloudSetup -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant SkipCloudSetup -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeSiriSetup -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeePrivacy -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeAppearanceSetup -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeScreenTime -bool true
sudo -u "$U" defaults write com.apple.SetupAssistant DidSeeAccessibility -bool true

sudo -u "$U" defaults write com.apple.Siri StatusMenuVisible -bool false
sudo -u "$U" defaults write com.apple.Siri SiriEnabled -bool false
sudo -u "$U" defaults write com.apple.dock show-recents -bool false
sudo -u "$U" defaults write com.apple.finder CreateDesktop -bool false

# Sleep image would write RAM to NVMe. Machine-wide; Self-Destruct restores this.
sudo pmset -a sleep 0 disablesleep 1 hibernatemode 0
sudo -u "$U" defaults write com.apple.screensaver idleTime -int 0


sudo tee /usr/local/bin/create_ramdisk.sh << 'EOF'
#!/bin/zsh
set -euo pipefail

OWNER=entropylab
VOL=/Volumes/RAMDISK
SECTORS=$((1024 * 2048))  # 1 GiB

if [ -d "$VOL/chrome" ]; then
  chown -R "$OWNER":staff "$VOL"
  chmod 700 "$VOL/chrome"
  exit 0
fi

DEV=$(hdiutil attach -nomount "ram://${SECTORS}" | tr -d '[:space:]')
if ! diskutil erasevolume APFS RAMDISK "$DEV"; then
  diskutil erasevolume HFS+ RAMDISK "$DEV"
fi

mkdir -p "$VOL/chrome"
chown -R "$OWNER":staff "$VOL"
chmod 700 "$VOL/chrome"
EOF
sudo chmod 755 /usr/local/bin/create_ramdisk.sh
sudo chown root:wheel /usr/local/bin/create_ramdisk.sh

sudo tee /Library/LaunchDaemons/com.entropylab.ramdisk.plist << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.entropylab.ramdisk</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/create_ramdisk.sh</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/var/log/entropylab-ramdisk.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/entropylab-ramdisk.log</string>
</dict>
</plist>
EOF
sudo chown root:wheel /Library/LaunchDaemons/com.entropylab.ramdisk.plist
sudo chmod 644 /Library/LaunchDaemons/com.entropylab.ramdisk.plist

sudo launchctl bootout system/com.entropylab.ramdisk 2>/dev/null || true
sudo launchctl bootstrap system /Library/LaunchDaemons/com.entropylab.ramdisk.plist
sudo launchctl enable system/com.entropylab.ramdisk
sudo launchctl kickstart -k system/com.entropylab.ramdisk


sudo tee /Users/entropylab/bin/launch_browser.sh << 'EOF'
#!/bin/zsh
set -euo pipefail

for i in {1..30}; do
  [ -d /Volumes/RAMDISK/chrome ] && break
  sleep 1
done
if [ ! -d /Volumes/RAMDISK/chrome ]; then
  osascript -e 'display notification "RAM disk missing" with title "EntropyLab"'
  exit 1
fi

APP="/Applications/Chromium.app"
if [ ! -d "$APP" ]; then
  APP="/Applications/Google Chrome.app"
fi
if [ ! -d "$APP" ]; then
  osascript -e 'display notification "Install Chromium or Google Chrome first" with title "EntropyLab"'
  exit 1
fi

HTML="/Users/entropylab/entropylab.html"

open -a "$APP" --args \
  --incognito \
  --no-first-run \
  --no-default-browser-check \
  --disable-sync \
  --disable-extensions \
  --disable-component-update \
  --disable-notifications \
  --disable-infobars \
  --noerrdialogs \
  --disable-session-crashed-bubble \
  --disable-features=TranslateUI \
  --password-store=basic \
  --use-mock-keychain \
  --start-fullscreen \
  --user-data-dir=/Volumes/RAMDISK/chrome \
  "file://${HTML}"
EOF

sudo chown -R entropylab:staff /Users/entropylab/bin
sudo chmod 755 /Users/entropylab/bin/launch_browser.sh


sudo tee /Users/entropylab/Library/LaunchAgents/com.entropylab.browser.plist << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.entropylab.browser</string>
    <key>ProgramArguments</key>
    <array>
        <string>/Users/entropylab/bin/launch_browser.sh</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
EOF
sudo chown -R entropylab:staff /Users/entropylab/Library
sudo chmod 644 /Users/entropylab/Library/LaunchAgents/com.entropylab.browser.plist


sudo tee /usr/local/bin/cleanup_entropylab.sh << 'EOF'
#!/bin/zsh
set -eu

pmset -a sleep 10 disablesleep 0 hibernatemode 3

launchctl bootout system/com.entropylab.ramdisk 2>/dev/null || true
rm -f /Library/LaunchDaemons/com.entropylab.ramdisk.plist
rm -f /usr/local/bin/create_ramdisk.sh

if mount | grep -q ' /Volumes/RAMDISK '; then
  diskutil eject /Volumes/RAMDISK || true
fi

# Drop the sudoers rule before deleting the user
rm -f /etc/sudoers.d/entropylab_cleanup

chflags nouchg /Users/entropylab/entropylab.html 2>/dev/null || true
sysadminctl -deleteUser entropylab -secure

/sbin/shutdown -r now
EOF
sudo chown root:wheel /usr/local/bin/cleanup_entropylab.sh
sudo chmod 755 /usr/local/bin/cleanup_entropylab.sh

printf '%s\n' 'entropylab ALL=(root) NOPASSWD: /usr/local/bin/cleanup_entropylab.sh' \
  | sudo tee /etc/sudoers.d/entropylab_cleanup
sudo chown root:wheel /etc/sudoers.d/entropylab_cleanup
sudo chmod 440 /etc/sudoers.d/entropylab_cleanup
sudo visudo -cf /etc/sudoers.d/entropylab_cleanup

sudo tee /Users/entropylab/Self-Destruct.command << 'EOF'
#!/bin/zsh
/usr/bin/sudo /usr/local/bin/cleanup_entropylab.sh
EOF
sudo chown entropylab:staff /Users/entropylab/Self-Destruct.command
sudo chmod 755 /Users/entropylab/Self-Destruct.command

sudo -u entropylab defaults write com.apple.dock persistent-others -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>file:///Users/entropylab/Self-Destruct.command</string><key>_CFURLStringType</key><integer>15</integer></dict></dict><key>tile-type</key><string>file-tile</string></dict>'
sudo -u entropylab killall Dock 2>/dev/null || true
